sequenceDiagram
    actor User as Utilisateur
    participant Front as Frontend
    participant Back as Backend
    participant Mongo as MongoDB
    participant HDFS as HDFS
    participant Air as Airflow

    Note over User,Air: Upload (Bronze)
    User->>Front: Upload document (PDF/image)
    Front->>Back: POST /api/upload
    Back->>Mongo: Sauvegarder metadata (status: uploaded)
    Back->>HDFS: Ecrire dans /raw/{id}/ (Bronze)
    Back->>Air: Trigger DAG (document_id)
    Back-->>Front: 200 OK

    Note over User,Air: Traitement — Bronze → Silver
    Air->>Mongo: status → processing
    Air->>HDFS: Lire fichier brut /raw/{id}/ (Bronze)
    Air->>Air: OCR (extract_text)
    Air->>HDFS: Ecrire texte OCR /clean/{id}/ (Silver)

    Note over User,Air: Traitement — Silver → Gold
    Air->>Air: NER (extract_entities)
    Air->>Air: Classification (classify_document)
    Air->>Air: Validation (validate_coherence)
    Air->>HDFS: Ecrire JSON enrichi /curated/{id}/ (Gold)
    Air->>Mongo: status → completed + resultats IA

    Note over User,Air: Consultation
    User->>Front: Ouvre dashboard
    Front->>Back: GET /api/documents
    Back->>Mongo: Lire documents
    Back-->>Front: Liste + statuts
    User->>Front: Clique document
    Front->>Back: GET /api/documents/{id}
    Back-->>Front: OCR, entites, anomalies
    Front-->>User: Affiche resultats
